version: '3.8'
services:
  web:
    image: dress-rental-web:v1
    build:
      context: ./dress-rental-web-app
      dockerfile: Dockerfile
    ports:
      - 8888
    volumes:
    - /home/carpeat/development/config:/config
    depends_on:
      - rest

  rest:
    container_name: rest
    image: dress-rental-rest:v1
    build:
      context: ./dress-rental-rest-app
      dockerfile: Dockerfile
    ports:
      - 8088:8088

  nginx:
    image: nginx:1.19.1-alpine
    container_name: nginx
    volumes:
      - /home/carpeat/development/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8989:8989
    depends_on:
      - web
